Repository Vinnyumc/Vinny-backend, pull requests merged in 2025-07, with the labels that each got.

#7 [Feat/#5] Common domain BaseEntity 생성 (진짜)
  src/main/java/com/vinny/backend/Common/domain/BaseEntity.java
Labels: ✨feat

#11 ✨[Feat/#9] Login 관련 엔티티 생성
  .gitignore
  src/main/java/com/vinny/backend/User/domain/Agreement.java
  src/main/java/com/vinny/backend/User/domain/Brand.java
  src/main/java/com/vinny/backend/User/domain/Region.java
  src/main/java/com/vinny/backend/User/domain/SearchLog.java
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/User/domain/VintageItem.java
  src/main/java/com/vinny/backend/User/domain/VintageStyle.java
  src/main/java/com/vinny/backend/User/domain/enums/UserStatus.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserAgreement.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserBrand.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserRegion.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserVintageItem.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserVintageStyle.java
Labels: ✨feat

#14 🐛 [Fix/#9] User 엔티티의 userStatus 필드 타입 오류 수정
  src/main/java/com/vinny/backend/User/domain/User.java
Labels: 🐛fix

#3 ✨[feat/#2] 커뮤니티 관련 도메인 구조 생성 및 엔티티 구현
  src/main/java/com/vinny/backend/common/domain/BaseEntity.java
  src/main/java/com/vinny/backend/post/domain/Like.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/domain/PostBrandHashtag.java
  src/main/java/com/vinny/backend/post/domain/PostImage.java
  src/main/java/com/vinny/backend/post/domain/PostImageId.java
  src/main/java/com/vinny/backend/post/domain/PostShopHashtag.java
  src/main/java/com/vinny/backend/post/domain/PostStyleHashtag.java
Labels: ✨feat

#20 🐛 [Fix/#19] Common 디렉토리 대소문자 오류 수정
  src/main/java/com/vinny/backend/Common/domain/BaseEntity.java
  src/main/java/com/vinny/backend/Shop/domain/RegionCategory.java
  src/main/java/com/vinny/backend/Shop/domain/Review.java
  src/main/java/com/vinny/backend/Shop/domain/ReviewImage.java
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
  src/main/java/com/vinny/backend/Shop/domain/ShopStyle.java
  src/main/java/com/vinny/backend/Shop/domain/Style.java
  src/main/java/com/vinny/backend/User/domain/Agreement.java
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserAgreement.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserBrand.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserRegion.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserVintageItem.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserVintageStyle.java
  src/main/java/com/vinny/backend/common/domain/BaseEntity.java
Labels: 🐛fix

#26 🐛[Fix/#25] ApiResponse 성공한 경우 응답 생성 주석 해제
  src/main/java/com/vinny/backend/error/ApiResponse.java
Labels: 🐛fix

#22 🐛[Fix/#21] 스타일, 지역 카테고리 중복 테이블 수정
  src/main/java/com/vinny/backend/Shop/domain/RegionCategory.java
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
  src/main/java/com/vinny/backend/Shop/domain/ShopStyle.java
  src/main/java/com/vinny/backend/Shop/domain/Style.java
  src/main/java/com/vinny/backend/Shop/domain/mapping/ShopVintageStyle.java
Labels: 🐛fix

#24 🐛[Fix/#23] Like 클래스 User 임포트 추가
  src/main/java/com/vinny/backend/post/domain/Like.java
Labels: 🐛fix

#28 ✨[Feat/#27] Spring Security + JWT 인증 구조 구현
  build.gradle
  src/main/java/com/vinny/backend/BackendApplication.java
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/User/repository/UserRepository.java
  src/main/java/com/vinny/backend/auth/controller/AuthController.java
  src/main/java/com/vinny/backend/auth/dto/KakaoLoginRequestDto.java
  src/main/java/com/vinny/backend/auth/dto/TokenDto.java
  src/main/java/com/vinny/backend/auth/dto/TokenRequestDto.java
  src/main/java/com/vinny/backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/vinny/backend/auth/jwt/JwtProvider.java
  src/main/java/com/vinny/backend/auth/service/AuthService.java
  src/main/java/com/vinny/backend/config/SecurityConfig.java
  src/main/java/com/vinny/backend/post/domain/Like.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/domain/PostBrandHashtag.java
  src/main/java/com/vinny/backend/post/domain/PostShopHashtag.java
  src/main/java/com/vinny/backend/post/domain/PostStyleHashtag.java
  src/main/resources/application-local.yaml
Labels: ✨feat

#30 ✨[Feat/#29] ShopImage 테이블 추가
  src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
Labels: ✨feat

#34 ✨[Feat/#33] UserShop 엔티티 추가
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/User/domain/enums/UserShopStatus.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserShop.java
Labels: ✨feat

#39 🐛[Fix/#38] ShopImage H2 문법 오류
  src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
Labels: 🐛fix

#47 ✨ [Feat/#45] 검색 기능 api Controller 및 DTO 구현
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/dto/ShopSearchResponseDto.java
  src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
  src/main/java/com/vinny/backend/config/SecurityConfig.java
  src/main/java/com/vinny/backend/post/controller/PostController.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/dto/PostSearchResponseDto.java
  src/main/java/com/vinny/backend/post/repsitory/PostRepository.java
  src/main/java/com/vinny/backend/post/service/PostService.java
Labels: ✨feat

#44 [Feat/#41] 가게 생성 api
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
  src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
  src/main/java/com/vinny/backend/Shop/domain/mapping/ShopVintageStyle.java
  src/main/java/com/vinny/backend/Shop/dto/ShopRequestDto.java
  src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java
  src/main/java/com/vinny/backend/Shop/repository/ShopImageRepository.java
  src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
  src/main/java/com/vinny/backend/Shop/service/ShopCommandService.java
  src/main/java/com/vinny/backend/Shop/service/ShopCommandServiceImpl.java
  src/main/java/com/vinny/backend/User/repository/RegionRepository.java
  src/main/java/com/vinny/backend/User/repository/VintageStyleRepository.java
  src/main/java/com/vinny/backend/User/validation/annotation/ExistRegion.java
  src/main/java/com/vinny/backend/User/validation/annotation/ExistVintageStyle.java
  src/main/java/com/vinny/backend/User/validation/validator/RegionExistValidator.java
  src/main/java/com/vinny/backend/User/validation/validator/VintageStyleExistValidator.java
Labels: ✨feat

#53 🔧[Chore/#52] CI/CD 스크립트 추가
  .github/workflows/dev_deploy.yml
Labels: 🔧chore

#51 ✨[Feat/#48] 피드 전체 조회 api
  src/main/java/com/vinny/backend/post/controller/PostController.java
  src/main/java/com/vinny/backend/post/converter/PostConverter.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/domain/mapping/PostBrandHashtag.java
  src/main/java/com/vinny/backend/post/domain/mapping/PostShopHashtag.java
  src/main/java/com/vinny/backend/post/domain/mapping/PostStyleHashtag.java
  src/main/java/com/vinny/backend/post/domain/mapping/UserPost.java
  src/main/java/com/vinny/backend/post/dto/PostResponseDto.java
  src/main/java/com/vinny/backend/post/repository/PostRepository.java
  src/main/java/com/vinny/backend/post/service/PostService.java
Labels: ✨feat

#55 ✨[feat/#54] 알림 엔티티 생성
  src/main/java/com/vinny/backend/notification/domain/Notification.java
Labels: ✨feat

#50 ✨[Feat/#49] 스타일별 가게 목록 조회 (페이징) api
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java
  src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
  src/main/java/com/vinny/backend/User/repository/VintageStyleRepository.java
  src/main/java/com/vinny/backend/User/validation/validator/VintageStyleExistValidator.java
  src/main/java/com/vinny/backend/common/validator/ValidPageParam.java
  src/main/java/com/vinny/backend/common/validator/ValidPageParamResolver.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
Labels: ✨feat

#58 🔧[Chore/#57] AWS S3 환경 구축
  .gitignore
  build.gradle
  src/main/java/com/vinny/backend/config/S3Config.java
  src/main/java/com/vinny/backend/config/SecurityConfig.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
  src/main/java/com/vinny/backend/s3/controller/FileUploadController.java
  src/main/java/com/vinny/backend/s3/service/S3Service.java
  src/main/resources/application-local.yaml
Labels: 🔧chore

#64 🔧[Chore/#63] .env 파일 및 application.yml 환경변수 관리 개선
  .gitignore
  src/main/resources/application-local.yaml
Labels: 🔧chore

#62 🔧[Chore/#57] doker 설정
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: 🔧chore

#67 🔧[Chore/#56] dev_deploy 수정
  .github/workflows/dev_deploy.yml
Labels: 🔧chore

#70 🔧[Chore/#68] CI/CD 파일 수정
  .github/workflows/dev_deploy.yml
  Dockerfile
Labels: 🔧chore

#72 🔧[Chore/#71] CI/CD 파일 수정- dev_deploy.yml
  .github/workflows/dev_deploy.yml
Labels: 🔧chore

#82 🔧 [Chore] CI/CD build 오류 개선 및 docker-compose 수정
  .github/workflows/dev_deploy.yml
  docker-compose.yml
Labels: 🔧chore

#86 🔧[Chore/#85] aws-jwt-secret 추가
  .github/workflows/dev_deploy.yml
  src/main/resources/application-local.yaml
Labels: 🔧chore

#92 ✨[Feat/#59] 가게 상세 조회 api
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
  src/main/resources/application-local.yaml
Labels: ✨feat

#91 ✨ [feat] 최근 검색어 추가 api 설계
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
  src/main/java/com/vinny/backend/search/controller/SearchLogController.java
  src/main/java/com/vinny/backend/search/dto/SearchLogCreateRequest.java
  src/main/java/com/vinny/backend/search/dto/SearchLogResponse.java
  src/main/java/com/vinny/backend/search/repository/SearchLogRepository.java
  src/main/java/com/vinny/backend/search/service/SearchLogService.java
Labels: ✨feat

#100 🐛[Fix/#99] 가게 후기 작성 api imageURL S3 설정
  src/main/java/com/vinny/backend/Shop/controller/ReviewController.java
  src/main/java/com/vinny/backend/Shop/dto/ReviewRequestDto.java
  src/main/java/com/vinny/backend/Shop/service/ReviewService.java
Labels: 🐛fix

#106 ✨[Feat/#105] 최근 검색어 조회 api 구현
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/error/ApiResponse.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
  src/main/java/com/vinny/backend/search/controller/SearchLogController.java
  src/main/java/com/vinny/backend/search/domain/SearchLog.java
  src/main/java/com/vinny/backend/search/dto/RecentSearchListResponse.java
  src/main/java/com/vinny/backend/search/dto/RecentSearchResponse.java
  src/main/java/com/vinny/backend/search/dto/SearchLogDeleteRequest.java
  src/main/java/com/vinny/backend/search/dto/SearchLogDeleteResponse.java
  src/main/java/com/vinny/backend/search/dto/SearchLogResponse.java
  src/main/java/com/vinny/backend/search/repository/SearchLogRepository.java
  src/main/java/com/vinny/backend/search/service/SearchLogService.java
Labels: ✨feat

#109 ✨[Feat/#102] 가게 즐겨찾기 관련 api
  src/main/java/com/vinny/backend/User/controller/UserShopController.java
  src/main/java/com/vinny/backend/User/domain/mapping/UserShop.java
  src/main/java/com/vinny/backend/User/dto/UserShopRequestDto.java
  src/main/java/com/vinny/backend/User/dto/UserShopResponseDto.java
  src/main/java/com/vinny/backend/User/repository/UserShopRepository.java
  src/main/java/com/vinny/backend/User/service/UserShopService.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
Labels: ✨feat

#114 ✨[feat/#113] 게시물 좋아요, 북마크 추가/삭제
  src/main/java/com/vinny/backend/error/ApiResponse.java
  src/main/java/com/vinny/backend/post/controller/PostController.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/domain/mapping/UserPostBookmark.java
  src/main/java/com/vinny/backend/post/domain/mapping/UserPostLike.java
  src/main/java/com/vinny/backend/post/repository/PostRepository.java
  src/main/java/com/vinny/backend/post/repository/UserPostBookmarkRepository.java
  src/main/java/com/vinny/backend/post/repository/UserPostLikeRepository.java
  src/main/java/com/vinny/backend/post/service/PostBookmarkService.java
  src/main/java/com/vinny/backend/post/service/PostLikeService.java
Labels: ✨feat
