Repository Vinnyumc/Vinny-backend, pull requests merged in 2025-08, with the labels that each got.

#112 ✨[feat/#111]게시글 수정 및 삭제 기능
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
  src/main/java/com/vinny/backend/post/controller/PostController.java
  src/main/java/com/vinny/backend/post/domain/Post.java
  src/main/java/com/vinny/backend/post/dto/PostRequestDto.java
  src/main/java/com/vinny/backend/post/repository/PostRepository.java
  src/main/java/com/vinny/backend/post/service/PostService.java
Labels: ✨feat

#128 🔧[Chore/#127] docker-compose 및 rds 설정 yaml 추가
  docker-compose.yml
  src/main/resources/application-prod.yaml
Labels: 🔧chore

#120 ✨[Feat/#116] 가게 후기 조회, 삭제 api
  src/main/java/com/vinny/backend/Shop/controller/ReviewController.java
  src/main/java/com/vinny/backend/Shop/repository/ReviewRepository.java
  src/main/java/com/vinny/backend/Shop/service/ReviewService.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
Labels: ✨feat

#122 ✨ [Feat/#118] 마이페이지 게시글 및 찜한 샵 조회 API 구현
  src/main/java/com/vinny/backend/Mypage/Controller/MypageController.java
  src/main/java/com/vinny/backend/Mypage/Service/MypageService.java
  src/main/java/com/vinny/backend/Mypage/dto/MypageLikedShopResponse.java
  src/main/java/com/vinny/backend/Mypage/dto/MypagePostThumbnailResponse.java
  src/main/java/com/vinny/backend/User/repository/UserShopRepository.java
  src/main/java/com/vinny/backend/post/repository/PostRepository.java
  src/main/java/com/vinny/backend/post/service/PostService.java
Labels: ✨feat

#135 ✨[Feat/#132] 가게 상세조회 Dto 수정, 지도용 가게 썸네일 조회 추가
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java
  src/main/java/com/vinny/backend/Shop/dto/ShopVintageStyleDto.java
  src/main/java/com/vinny/backend/Shop/service/ShopCommandServiceImpl.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
  src/main/java/com/vinny/backend/config/SecurityConfig.java
Labels: ✨feat

#142 🔧[chore] CORS 허용 경로 추가
  src/main/java/com/vinny/backend/config/SecurityConfig.java
Labels: 🔧chore

#146 ♻️[Refactor/#145] 가게 관련 api 스웨거 수정 및 삭제
  src/main/java/com/vinny/backend/Shop/controller/ReviewController.java
  src/main/java/com/vinny/backend/Shop/controller/ShopController.java
  src/main/java/com/vinny/backend/Shop/dto/ReviewRequestDto.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
  src/main/java/com/vinny/backend/User/controller/UserShopController.java
  src/main/java/com/vinny/backend/User/service/UserShopService.java
  src/main/java/com/vinny/backend/common/validator/ValidPageParamResolver.java
  src/main/java/com/vinny/backend/config/WebConfig.java
  src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
Labels: ♻️refactor

#162 ✨[feat] 앱 부팅용 세션 확인 API 구현
  src/main/java/com/vinny/backend/auth/controller/AuthController.java
  src/main/java/com/vinny/backend/auth/dto/SessionResponseDto.java
  src/main/java/com/vinny/backend/auth/service/AuthService.java
  src/main/java/com/vinny/backend/config/SecurityConfig.java
Labels: ✨feat

#159 ✨[feat]게시글 작성시 목록 조회 및 검색
  src/main/java/com/vinny/backend/User/repository/BrandRepository.java
  src/main/java/com/vinny/backend/brand/controller/BrandController.java
  src/main/java/com/vinny/backend/brand/dto/BrandDto.java
  src/main/java/com/vinny/backend/brand/service/BrandService.java
  src/main/java/com/vinny/backend/style/controller/StyleController.java
  src/main/java/com/vinny/backend/style/dto/StyleDto.java
  src/main/java/com/vinny/backend/style/repository/StyleRepository.java
  src/main/java/com/vinny/backend/style/service/StyleService.java
Labels: ✨feat

#166 🐛 [fix] 온보딩 request 닉네임, 코멘트 추가
  src/main/java/com/vinny/backend/User/domain/User.java
  src/main/java/com/vinny/backend/User/dto/OnboardingRequestDto.java
  src/main/java/com/vinny/backend/User/service/UserService.java
Labels: 🐛fix

#196 🐛 [fix] AuthController 401 에러 처리 수정
  src/main/java/com/vinny/backend/auth/controller/AuthController.java
Labels: 🐛fix

#204 ♻️[Refactor/#203] Shop image 필드 변경
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
  src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java
  src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
Labels: ♻️refactor

#212 ♻️[Refactor/#211] Home api /regenerate 제외
  src/main/java/com/vinny/backend/User/controller/UserShopForYouController.java
Labels: ♻️refactor

#214 🐛 [Fix/#213] Map Api Response 대표스타일 추가
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
  src/main/java/com/vinny/backend/map/converter/MapConverter.java
  src/main/java/com/vinny/backend/map/dto/MapResponseDto.java
Labels: 🐛fix

#216 [Feat/#215] shop entity logo_image 필드 추가
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
  src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java
  src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
Labels: ✨feat

#218 🐛[Fix/#217] logoImage length 수정
  src/main/java/com/vinny/backend/Shop/domain/Shop.java
Labels: 🐛fix

#228 ✨[FEAT/#123] 애플 소셜 로그인 연동
  .gitignore
  src/main/java/com/vinny/backend/auth/controller/AuthController.java
  src/main/java/com/vinny/backend/auth/dto/ApplePublicKeyResponse.java
  src/main/java/com/vinny/backend/auth/dto/AppleTokenRequestDto.java
  src/main/java/com/vinny/backend/auth/dto/AppleTokenResponse.java
  src/main/java/com/vinny/backend/auth/dto/AppleUserPayload.java
  src/main/java/com/vinny/backend/auth/jwt/AppleJwtUtils.java
  src/main/java/com/vinny/backend/auth/service/AppleAuthService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/static/index.html
Labels: ✨feat

#231 [Refactor/#229] 가게 상세 조회 수정
  src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java
  src/main/java/com/vinny/backend/Shop/service/ShopService.java
Labels: ♻️refactor

#242 🐛[FIX/#237] 애플 로그인 버그 수정
  build.gradle
  src/main/java/com/vinny/backend/auth/controller/AuthController.java
  src/main/java/com/vinny/backend/auth/dto/AppleTokenRequestDto.java
  src/main/java/com/vinny/backend/auth/jwt/AppleJwtUtils.java
  src/main/java/com/vinny/backend/auth/jwt/JwtProvider.java
  src/main/java/com/vinny/backend/auth/service/AppleAuthService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/static/index.html
Labels: 🐛fix

#252 [Feat/#251] 유저 온보딩 reset시 홈 취향저격 리스트 즉시 반영
  src/main/java/com/vinny/backend/User/config/AsyncConfig.java
  src/main/java/com/vinny/backend/User/config/UserPreferenceChangedEvent.java
  src/main/java/com/vinny/backend/User/config/WeeklyRegenListener.java
  src/main/java/com/vinny/backend/User/controller/UserShopForYouController.java
  src/main/java/com/vinny/backend/User/repository/UserShopForYouRepository.java
  src/main/java/com/vinny/backend/User/service/UserService.java
  src/main/java/com/vinny/backend/User/service/UserShopForYouService.java
Labels: ✨feat
